name: test
on: push
jobs:
        test:
                runs-on: ubuntu-18.04
                container:ryuichiueda/ubuntu18.04-ros2:latest
                steps:
                        - uses:actions/checout@v2
                        - name:build and test
                run: |
                        rsync -av ./ /root/ros2_ws/src/mypkg
                        cd /root/ros2_es
                        rosdep update
                        rosdep install -i --form-path src --rosdistro humble -y
                        bash -xv ./src/mypkg/test/test.bash /root
